version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build_and_test:
    docker:
      - image: cimg/node:17.2.0
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          NODE_ENV: test
          SECRET: xyufyigbnkm
          SALT_ROUNDS: 3
          ROLE: admin
      - image: postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circleci
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm test
          name: Run tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  test_my_app:
    jobs:
      - build_and_test
